### ISSUE TITLE
get_gutter_width issues: scrolling & view shifts

### ISSUE THREAD

**Issue by romgrk** [romgrk/nvim-treesitter-context#22]
With #21 merged, issue #16 might be back oon some edge cases.

Reference: https://github.com/romgrk/nvim-treesitter-context/pull/21#issuecomment-752807647

**Comment by seandewar** [comment]
As an aside, some considerations for the future:

- **Not really necessary:** `OptionSet` `autocmd`s for `scl`, `fdc`, `nu`, `rnu`, `nuw` to trigger a resize for an open context window, as these options can potentially change the size of the gutter when modified.
- **Probably not doable yet:** An `autocmd` event/callback to hook into for gutter changes, so that an open context window can be resized appropriately _whenever_ the gutter's size changes. Would presumably supersede the `OptionSet` `autocmd`s, too.

**Comment by lewis6991** [comment]
Getting gutter width is now quite reliable with this:

```lua
local function get_gutter_width()
  return vim.fn.getwininfo(vim.api.nvim_get_current_win())[1].textoff
end
```
