### ISSUE TITLE
Cursor is hidden behing context window

### ISSUE THREAD

**Issue by nkcfan** [romgrk/nvim-treesitter-context#28]
I use `zt` to scroll the current line to the top. A normal use case is to check a code block inside a long function.

However the top line will be overlapped by context line and this is annoying. Suggest remap `zt` to move the scroll the current line to the 2nd top line.

**Comment by romgrk** [comment]
I'll see what we can do, I wouldn't be comfortable remapping fundamentals such as `zt` but we could provide a context-aware zt alternative for you to map to.

**Comment by lucc** [comment]
I have experienced this bug as well (the cursor being behind the float window). I would say this is more general then just a conflict with `zt`. You can see this behaviour with any/many? movements that move the cursor to a line that is visible in the screen area of the current window but hidden behind the floating window.

In order to test this you need any buffer with a deep enough context, for example `lua/treesitter-context.lua` from this repo. I am using bdc598b519cfbfdf61baf9a27953da2fc1642b23 so I am positioning line 77 at the top of my window (`:77Gzt` in neovim). Now you can move the cursor around (as long as the window does not scroll) and see it hiding behind the floating window and reappearing for example type `82G` and then `78G`. Or `:79<CR>` and then `:77<CR>`. You could even move up and done a litte with `j` and `k`.

The point is that you would have to remap everything. And I guess that will lead to conflicts with all kind of configs or plugins. I think the correct approach would be to find a more general solution. 
## Idea
The area hidden by the float feel as if it does not belong to my current window so the window should be scrolled when entering this area:
- detect the size of the context window and check if the widow-line of the cursor is behind it 
- scroll the current window until the current line is below the floating window
## Question/Problem
Will it be possible to run in an endless loop?  Some hypothetical situation where
  - the cursor is hidden
  - the window gets scrolled 
  - but that changes the size of the context to display 
  - so we should actually "undo" the scroll 
  - but when the scroll is undone, the context gets bigger again and hides the cursor again
 But maybe such a situation is impossible, I did not think it through.

**Comment by romgrk** [comment]
I did something. Let me know if it's still a problem for you.

**Comment by romgrk** [comment]
Had to revert the changes.

**Comment by zeertzjq** [comment]
I think the title of this issue can be changed to be more general.

**Comment by Jasha10** [comment]
Perhaps as a workaround we could update the buffer-local `&scrolloff` setting to prevent the cursor from overlapping with the context window.

This approach has the drawback that `scrolloff` affects both the top *and* the bottom of the window.

If this approach is acceptable to those in charge here, I'll try to open a PR with such a patch.
