### ISSUE TITLE
Conflict with session plugins

### ISSUE THREAD

**Issue by nsxz1234** [romgrk/nvim-treesitter-context#68]
[https://github.com/rmagatti/auto-session](url),
[https://github.com/Shatur/neovim-session-manager](url)

**Comment by romgrk** [comment]
Please elaborate on the issue.

**Comment by GustavoKatel** [comment]
I was having some issues when using both this plugin and `rmagatti/auto-session`. The issue was that after restoring the session, the ui was clamped to the size of the floating window (or something like that).

![image](https://user-images.githubusercontent.com/1891977/135947496-2b3f6959-290e-4bbe-b831-55e632a415db.png)

`:resize` fixed the ui, but it was annoying.

the real fix was to disable/close the floating window before saving the session, like this

```lua
local function disable_ts_context()
	require("treesitter-context").disable()
end

autosession.setup({
        ...
	auto_session_enabled = true,
	pre_save_cmds = { disable_ts_context }, -- call the custom hook here
})
```

not sure if it was OP's issue, but maybe this helps

**Comment by romgrk** [comment]
Nothing that I can do here, session plugins are handling floating windows badly. The enable/disable is the way to go, I also use the same mechanism with my own session plugin.
